### ISSUE TITLE
Can't download Bangla corpus 

### ISSUE THREAD

**Issue by robi56** [mehedihasanbijoy/DPCSpell#1]
Hi this is a very good work. 

Data can't get from the following drive link 
https://drive.google.com/drive/folders/1vfCAqqXy0ZTL8cPKR-K5q5coBnNv2Zxf?usp=sharing

gdown https://drive.google.com/drive/folders/1vfCAqqXy0ZTL8cPKR-K5q5coBnNv2Zxf?usp=sharing -O ./Dataset --folder

Please share the accessible link to download data

**Comment by mehedihasanbijoy** [comment]
Resolved
