### ISSUE TITLE
How to do inference

### ISSUE THREAD

**Issue by balajiselvaraj1601** [mehedihasanbijoy/DPCSpell#3]
I have bengali output saved in a csv file. I would like to do inference on the csv. Can you kindly let me know the code to use for the same ?

**Comment by mehedihasanbijoy** [comment]
Download the model checkpoints. Then, run the detector, purificator, and corrector modules with n_epochs = 0 (set the hyperparameter using --N_EPOCHS 0). For the detector module, you only need to run it with your corpus/CSV file. Finally, after running the corrector module, you should have the evaluation report.
